FROM node:18.16.0-alpine

ARG REACT_APP_SERVER_HOST
ENV REACT_APP_SERVER_HOST=${REACT_APP_SERVER_HOST}

WORKDIR /app
COPY . /app
RUN npm ci
RUN npm run build
RUN npm i express
RUN npm i path

CMD node /app/serve.prod.js