FROM node:18.16.0-alpine as install

WORKDIR /app
COPY . /app
RUN npm ci
RUN npm run build

FROM nginx:alpine as nginxrunner

COPY --from=install /app/build /build

RUN rm -rf /usr/share/nginx/html/*
RUN  cp -r /build/* /usr/share/nginx/html/
