FROM node:18.16.0-alpine as install

WORKDIR /app
COPY . /app
RUN npm ci
CMD npm run build



FROM nginx:alpine as nginxrunner

RUN rm -rf /usr/share/nginx/html/*

COPY ./build /app/build

RUN  cp -r /app/build/* /usr/share/nginx/html/
RUN  cp -r /app/build/assets /usr/share/nginx/html/assets/
